repos:
  - repo: local
    hooks:

      ### CODE FORMATTING

      - id: black
        name: black
        stages: [ pre-commit ]
        language: system
        entry: uv run black .
        types: [ python ]

      ### CODE STYLE ENFORCEMENT + SECURITY

      - id: ruff
        name: ruff
        stages: [ pre-commit ]
        language: system
        entry: uv run ruff check .
        types: [ python ]

      ### TYPE CHECKING

      - id: mypy
        name: mypy
        stages: [ pre-commit ]
        language: system
        entry: uv run mypy .
        types: [ python ]
        pass_filenames: false

      ### TESTING

      - id: pytest
        name: pytest
        stages: [ pre-push ]
        language: system
        entry: uv run pytest
        types: [ python ]
        pass_filenames: false
