### CODE FORMATTING

[tool.isort]
profile = "black"

[tool.black]
# https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#line-length
line-length = 100

### CODE STYLE ENFORCEMENT

[tool.flake8]
max-line-length = 100
ignore = ["E203", "E266", "E501", "W503"]
max-complexity = 18
select = ["B", "C", "E", "F", "W", "T4"]

### TYPE CHECKING

[tool.mypy]
files = "."
ignore_missing_imports = true

### SECURITY

[tool.bandit]
assert_used.skips = "*/tests/*"

### TESTING

[tool.pytest.ini_options]
addopts = "--cov --cov-fail-under=100"

[tool.coverage.run]
source = ["."]

[tool.coverage.report]
show_missing = true
omit = ["*/tests/*"]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "raise AssertionError",
    "raise NotImplementedError",
    "if __name__ == .__main__.:"
]
